from sqlalchemy import Boolean, Column, ForeignKey, Integer, String, Float, JSON
from sqlalchemy.orm import relationship
from ..core.database import Base

class Customer(Base):
    __tablename__ = "customers"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, index=True)
    email = Column(String, unique=True, index=True)
    age = Column(Integer)
    location = Column(String)
    data_gb = Column(Float, default=0.0)
    call_mins = Column(Integer, default=0)
    sms_count = Column(Integer, default=0)
    
    offers = relationship("CustomerOffer", back_populates="customer")

class Segment(Base):
    __tablename__ = "segments"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, index=True)
    description = Column(String)
    rules_json = Column(JSON)

class Offer(Base):
    __tablename__ = "offers"

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String, index=True)
    description = Column(String)
    eligibility_criteria = Column(JSON)
    channel = Column(String)

class CustomerOffer(Base):
    __tablename__ = "customer_offers"

    id = Column(Integer, primary_key=True, index=True)
    customer_id = Column(Integer, ForeignKey("customers.id"))
    offer_id = Column(Integer, ForeignKey("offers.id"))
    status = Column(String, default="pending")
    message = Column(String, nullable=True) # Personalized message generated by LLM

    customer = relationship("Customer", back_populates="offers")
    offer = relationship("Offer")
